# Generated by Django 4.2.15 on 2024-10-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
