# Generated by Django 4.2.15 on 2024-10-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0003_bookmark_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="user",
        ),
    ]
